server:
  disable: false
  http_listen_port: 0
  grpc_listen_port: 0
  log_level: error
positions:
  filename: /opt/mqtt_promtail/positions.yaml
clients:
  - url: ${MQTT_LOGGER_LOKI_CLIENT_URL}
scrape_configs:
  - job_name: mqtt_logger
    pipeline_stages:
      - json:
          expressions:
            mqtt_tst: tst
            mqtt_topic: topic
            mqtt_payload: payload
      - regex:
          expression: '(?P<mqtt_node>[^\/]*)'
          source: mqtt_topic
      - labels:
          mqtt_topic: null
          mqtt_node: null
      - timestamp:
          source: mqtt_tst
          format: '2006-01-02T15:04:05.000000-0700'
      - output:
          source: mqtt_payload
    static_configs:
      - targets:
          - localhost
        labels:
          job: mqtt_logger
          host_hostname: ${MQTT_LOGGER_HOST_HOSTNAME}
