- sensor:
    name: weatherflow_fetch_forecast
    command: bash /config/scripts/weatherflow/weatherflow_fetch_forecast.sh
    command_timeout: 30
    scan_interval: 300
- sensor:
    name: weatherflow_current_conditions
    json_attributes:
      - time
      - conditions
      - icon
      - air_temperature
      - sea_level_pressure
      - station_pressure
      - pressure_trend
      - relative_humidity
      - wind_avg
      - wind_direction
      - wind_direction_cardinal
      - wind_gust
      - solar_radiation
      - uv
      - brightness
      - feels_like
      - dew_point
      - wet_bulb_temperature
      - wet_bulb_globe_temperature
      - delta_t
      - air_density
      - lightning_strike_count_last_1hr
      - lightning_strike_count_last_3hr
      - lightning_strike_last_distance
      - lightning_strike_last_distance_msg
      - lightning_strike_last_epoch
      - precip_accum_local_day
      - precip_accum_local_yesterday
      - precip_minutes_local_day
      - precip_minutes_local_yesterday
      - is_precip_local_day_rain_check
      - is_precip_local_yesterday_rain_check
    command: bash /config/scripts/weatherflow/weatherflow_current_conditions.sh
    command_timeout: 30
    value_template: '{{ value_json.conditions }}'
    scan_interval: 300
- sensor:
    name: weatherflow_daily_forecast_0
    json_attributes:
      - day_num
      - month_num
      - conditions
      - icon
      - air_temp_high
      - air_temp_high_x
      - air_temp_low
      - air_temp_low_x
      - precip_probability
      - sunrise
      - sunset
      - day_name
    command: bash /config/scripts/weatherflow/weatherflow_forecast_daily.sh 0
    command_timeout: 30
    value_template: '{{ value_json.day_num }}'
    scan_interval: 300       
- sensor:
    name: weatherflow_daily_forecast_1
    json_attributes:
      - day_num
      - month_num
      - conditions
      - icon
      - air_temp_high
      - air_temp_high_x
      - air_temp_low
      - air_temp_low_x
      - precip_probability
      - sunrise
      - sunset
      - day_name
    command: bash /config/scripts/weatherflow/weatherflow_forecast_daily.sh 1
    command_timeout: 30
    value_template: '{{ value_json.day_num }}'
    scan_interval: 300
- sensor:
    name: weatherflow_daily_forecast_2
    json_attributes:
      - day_num
      - month_num
      - conditions
      - icon
      - air_temp_high
      - air_temp_high_x
      - air_temp_low
      - air_temp_low_x
      - precip_probability
      - sunrise
      - sunset
      - day_name
    command: bash /config/scripts/weatherflow/weatherflow_forecast_daily.sh 2
    command_timeout: 30
    value_template: '{{ value_json.day_num }}'
    scan_interval: 300
- sensor:
    name: weatherflow_daily_forecast_3
    json_attributes:
      - day_num
      - month_num
      - conditions
      - icon
      - air_temp_high
      - air_temp_high_x
      - air_temp_low
      - air_temp_low_x
      - precip_probability
      - sunrise
      - sunset
      - day_name
    command: bash /config/scripts/weatherflow/weatherflow_forecast_daily.sh 3
    command_timeout: 30
    value_template: '{{ value_json.day_num }}'
    scan_interval: 300
- sensor:
    name: weatherflow_daily_forecast_4
    json_attributes:
      - day_num
      - month_num            
      - conditions
      - icon
      - air_temp_high
      - air_temp_high_x
      - air_temp_low
      - air_temp_low_x
      - precip_probability
      - sunrise
      - sunset
      - day_name
    command: bash /config/scripts/weatherflow/weatherflow_forecast_daily.sh 4
    command_timeout: 30
    value_template: '{{ value_json.day_num }}'
    scan_interval: 300
- sensor:
    name: weatherflow_daily_forecast_5
    json_attributes:
      - day_num
      - month_num
      - conditions
      - icon
      - air_temp_high
      - air_temp_high_x
      - air_temp_low
      - air_temp_low_x
      - precip_probability
      - sunrise
      - sunset
      - day_name
    command: bash /config/scripts/weatherflow/weatherflow_forecast_daily.sh 5
    command_timeout: 30
    value_template: '{{ value_json.day_num }}'
    scan_interval: 300
- sensor:
    name: weatherflow_daily_forecast_6
    json_attributes:
      - day_num
      - month_num
      - conditions
      - icon
      - air_temp_high
      - air_temp_high_x
      - air_temp_low
      - air_temp_low_x
      - precip_probability
      - sunrise
      - sunset
      - day_name
    command: bash /config/scripts/weatherflow/weatherflow_forecast_daily.sh 6
    command_timeout: 30
    value_template: '{{ value_json.day_num }}'
    scan_interval: 300
- sensor:
    name: weatherflow_daily_forecast_7
    json_attributes:
      - day_num
      - month_num
      - conditions
      - icon
      - air_temp_high
      - air_temp_high_x
      - air_temp_low         
      - air_temp_low_x
      - precip_probability
      - sunrise
      - sunset
      - day_name
    command: bash /config/scripts/weatherflow/weatherflow_forecast_daily.sh 7
    command_timeout: 30
    value_template: '{{ value_json.day_num }}'
    scan_interval: 300
- sensor:
    name: weatherflow_daily_forecast_8
    json_attributes:
      - day_num
      - month_num
      - conditions
      - icon
      - air_temp_high
      - air_temp_high_x
      - air_temp_low
      - air_temp_low_x
      - precip_probability
      - sunrise
      - sunset
      - day_name
    command: bash /config/scripts/weatherflow/weatherflow_forecast_daily.sh 8
    command_timeout: 30
    value_template: '{{ value_json.day_num }}'
    scan_interval: 300
- sensor:
    name: weatherflow_daily_forecast_9
    json_attributes:
      - day_num
      - month_num
      - conditions
      - icon
      - air_temp_high
      - air_temp_high_x
      - air_temp_low
      - air_temp_low_x
      - precip_probability
      - sunrise
      - sunset
      - day_name
    command: bash /config/scripts/weatherflow/weatherflow_forecast_daily.sh 9
    command_timeout: 30
    value_template: '{{ value_json.day_num }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_0
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 0
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_1
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 1
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_2
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 2
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_3
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 3
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_4
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 4
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_5
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 5
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_6
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 6
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_7
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 7
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_8
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability   
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 8
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_9
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 9
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_10
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 10
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_11
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 11
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_12
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon      
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 12
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_13
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 13
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_14
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 14
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_15
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 15
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_16
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon                 
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 16
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_17
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 17
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_18
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 18
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_19
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 19
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_20
    json_attributes:
      - air_temperature
      - am_pm                
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 20
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_21
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 21
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_22
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 22
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
- sensor:
    name: weatherflow_hourly_forecast_23
    json_attributes:
      - air_temperature
      - am_pm
      - conditions
      - icon
      - local_hour
      - local_hour_icon
      - pixel_height
      - precip_probability
      - precip_probability_icon
    command: bash /config/scripts/weatherflow/weatherflow_forecast_hourly.sh 23
    command_timeout: 30
    value_template: '{{ value_json.local_hour }}'
    scan_interval: 300
