substitutions:
  devicename: esp03
esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32dev
logger:
  baud_rate: 0
switch:
  - platform: restart
    name: ${devicename} Restart
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
api: null
ota:
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${devicename}
    password: !secret wifi_password
  domain: .tylephony.com
  power_save_mode: none
captive_portal: null
web_server:
  port: 80
i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true
sensor:
  - platform: ccs811
    baseline: 11950
    eco2:
      name: ${devicename} CO2
    tvoc:
      name: ${devicename} TVOC
    address: 91
    temperature: ${devicename}_temperature
    humidity: ${devicename}_humidity
    update_interval: 60s
  - platform: bme280
    temperature:
      name: ${devicename} Temperature
      id: ${devicename}_temperature
      oversampling: 16x
    pressure:
      name: ${devicename} Pressure
      id: ${devicename}_pressure
    humidity:
      name: ${devicename} Humidity
      id: ${devicename}_humidity
    address: 119
    update_interval: 60s
    iir_filter: 16x
  - platform: wifi_signal
    name: ${devicename} WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: ${devicename} Uptime
    update_interval: 60s