substitutions:
  devicename: esp03
esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32dev
debug:
  update_interval: 60s
logger:
  baud_rate: 0
  level: DEBUG
switch:
  - platform: restart
    name: ${devicename} Restart
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
api: null
ota:
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${devicename}
    password: !secret wifi_password
  domain: .tylephony.com
  power_save_mode: none
captive_portal: null
web_server:
  port: 80
i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: True
    frequency: 100kHz
sensor:
  - platform: sps30
    i2c_id: bus_a
    pm_1_0:
      name: "${devicename} Workshop PM <1µm Weight concentration"
      id: "${devicename}_PM_1_0"
    pm_2_5:
      name: "${devicename} Workshop PM <2.5µm Weight concentration"
      id: "${devicename}_PM_2_5"
    pm_4_0:
      name: "${devicename} Workshop PM <4µm Weight concentration"
      id: "${devicename}_PM_4_0"
    pm_10_0:
      name: "${devicename} Workshop PM <10µm Weight concentration"
      id: "w${devicename}_PM_10_0"
    pmc_0_5:
      name: "${devicename} Workshop PM <0.5µm Number concentration"
      id: "${devicename}_PMC_0_5"
    pmc_1_0:
      name: "${devicename} Workshop PM <1µm Number concentration"
      id: "${devicename}_PMC_1_0"
    pmc_2_5:
      name: "${devicename} Workshop PM <2.5µm Number concentration"
      id: "${devicename}_PMC_2_5"
    pmc_4_0:
      name: "${devicename} Workshop PM <4µm Number concentration"
      id: "${devicename}_PMC_4_0"
    pmc_10_0:
      name: "${devicename} Workshop PM <10µm Number concentration"
      id: "${devicename}_PMC_10_0"
    pm_size:
      name: "${devicename} Typical Particle size"
      id: "${devicename}_pm_size"
    address: 0x69
    update_interval: 10s
  - platform: wifi_signal
    name: '${devicename} WiFi Signal'
    id: '${devicename}_WiFi_Signal'
    update_interval: 60s
  - platform: uptime
    name: '${devicename} Uptime'
    update_interval: 60s
  - platform: debug
    free:
      name: '${devicename} Heap Free'
    block:
      name: '${devicename} Heap Max Block'
    loop_time:
      name: '${devicename} Loop Time'
text_sensor:
  - platform: debug
    device:
      name: '${devicename} Device Info'
      id: '${devicename}_device_info'    