substitutions:
  devicename: esp08
esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32dev
logger:
  baud_rate: 0
switch:
  - platform: restart
    name: ${devicename} Restart
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
api: null
ota:
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${devicename}
    password: !secret wifi_password
  domain: .tylephony.com
  power_save_mode: none
captive_portal: null
web_server:
  port: 80
uart:
  rx_pin: GPIO16
  baud_rate: 9600
sensor:
  - platform: sm300d2
    co2:
      name: ${devicename} CO2
    formaldehyde:
      name: ${devicename} Formaldehyde
    tvoc:
      name: ${devicename} TVOC
    pm_2_5:
      name: ${devicename} PM2.5
    pm_10_0:
      name: ${devicename} PM10
    temperature:
      name: ${devicename} Temperature
    humidity:
      name: ${devicename} Humidity
    update_interval: 15s
  - platform: wifi_signal
    name: ${devicename} WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: ${devicename} Uptime
    update_interval: 60s