substitutions:
  devicename: esp05
esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32dev
logger:
  baud_rate: 0
switch:
  - platform: restart
    name: ${devicename} Restart
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
api: null
ota:
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${devicename}
    password: !secret wifi_password
  domain: .tylephony.com
  power_save_mode: none
captive_portal: null
web_server:
  port: 80

font:
  - file: "fonts/segoeui.ttf"
    id: segoe
    size: 64


spi:
  clk_pin: 13
  mosi_pin: 14

display:
  - platform: waveshare_epaper
    id: ${devicename}_epaper
    cs_pin: 33
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    model: 7.50inV2
    update_interval: 300s
    reset_duration: 2ms
    lambda: |-
      it.fill(COLOR_OFF);
      it.print(0,0,id(segoe), "Hello, World!");
      
      
sensor:
  
  - platform: wifi_signal
    name: "${devicename} WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: "${devicename} Uptime"
    update_interval: 60s