substitutions:
  devicename: esp13
esphome:
  name: '${devicename}'
esp32:
  board: featheresp32
  variant: esp32
external_components:
  - source: 'github://pr#3255'
    components:
      - display
      - online_image
      - waveshare_epaper
    refresh: 0s
debug:
  update_interval: 60s
time:
  - platform: homeassistant
    id: ntp
logger:
  baud_rate: 115200
  level: DEBUG
switch:
  - platform: restart
    name: '${devicename} Restart'
  - platform: gpio
    pin:
      number: 21
      inverted: 'yes'
    id: '${devicename}_reset_switch'
    internal: true
    name: '${devicename} Display Reset Pin'
api:
  reboot_timeout: 1min
ota:
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: '${devicename}'
    password: !secret wifi_password
  domain: .tylephony.com
  power_save_mode: none
spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15
display:
  - platform: waveshare_epaper
    id: '${devicename}_display'
    cs_pin: GPIO12
    busy_pin: GPIO33
    reset_pin: GPIO21
    dc_pin: GPIO27
    model: 7.50inV2
    update_interval: 60s
    reset_duration: 2ms
    lambda: |-
      // Start
      it.image(0, 0, id(example_image_1));
button:
  - platform: template
    name: '${devicename} Refresh'
    icon: 'mdi:update'
    on_press:
      then:
        - component.update: '${devicename}_display'
online_image:
  - url: 'http://attic.tylephony.com/forecast.png'
    id: example_image_1
    format: PNG
