esphome:
  name: hass-esp10
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  baud_rate: 0

switch:
  - platform: restart
    id: esp10_restart
    name: "esp10 Restart"

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "hass-esp10"
    password: "hass-esp10"

captive_portal:

web_server:
  port: 80

sensor:

  - platform: wifi_signal
    name: "esp10 WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: "esp10 Uptime"
    update_interval: 60s