esphome:
  name: hass-esp01
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  baud_rate: 0

switch:
  - platform: restart
    name: "esp01 Restart"

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  rx_pin: GPIO16
  baud_rate: 9600
#  rx_buffer_size: 1024

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO3
    num_leds: 16
    name: "esp01 Light"
    effects:
       - addressable_rainbow:
       - addressable_color_wipe:
       - addressable_scan:
       - addressable_twinkle:
       - addressable_random_twinkle:
       - addressable_fireworks:
       - addressable_flicker:

sensor:
  - platform: sm300d2
    co2:
      name: "esp01 CO2"
    formaldehyde:
      name: "esp01 Formaldehyde"
    tvoc:
      name: "esp01 TVOC"
    pm_2_5:
      name: "esp01 PM2.5"
    pm_10_0:
      name: "esp01 PM10"
    temperature:
      name: "esp01 Temperature"
    humidity:
      name: "esp01 Humidity"
    update_interval: 15s
    
  - platform: wifi_signal
    name: "esp01 WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: "esp01 Uptime"
    update_interval: 60s
