esphome:
  name: hass-esp05
  platform: ESP32
  board: nodemcu-32s

time:
  - platform: homeassistant
    id: esptime

# Enable logging
logger:
  baud_rate: 0
#  level: VERY_VERBOSE

switch:
  - platform: restart
    name: "esp05 Restart"

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "hass-esp05"
    password: "hass-esp05"

captive_portal:

web_server:
  port: 80

font:
  - file: "fonts/segoeui.ttf"
    id: segoe
    size: 64


spi:
  clk_pin: 13
  mosi_pin: 14

display:
  - platform: waveshare_epaper
    id: disp
    cs_pin: 33
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    model: 7.50in-bv2
    update_interval: 30s
    reset_duration: 2ms
    lambda: |-
      it.fill(COLOR_OFF);
      it.print(0,0,id(segoe), "Hello, World!");