esphome:
  name: hass-esp09
  platform: ESP32
  board: esp32dev
logger:
  baud_rate: 0
switch:
  - platform: restart
    id: esp09_restart
    name: esp09 Restart
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
api: null
ota:
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: hass-esp09
    password: hass-esp09
  domain: .tylephony.com
captive_portal: null
web_server:
  port: 80
sensor:
  - platform: wifi_signal
    name: esp09 WiFi Signal
    id: esp09_wifi_signal
    update_interval: 60s
  - platform: uptime
    name: esp09 Uptime
    update_interval: 60s
