blueprint:
  name: Zigbee2MQTT - Tuya 4-Button Scene Switch TS0044
  description: >
    Automate your Tuya 4-Button Scene Switch (TS0044) via Zigbee2MQTT.

    This blueprint allows you to configure actions for each button press type on
    the Tuya 4-Button Scene Switch (TS004F). The switch can be integrated with
    Home Assistant using Zigbee2MQTT. Each button supports single press, double
    press, and long press actions.

    **Instructions:**

    1. **Switch**: Select your Tuya 4-Button Scene Switch from the entity dropdown.

    2. **Base MQTT Topic**: By default, the base MQTT topic is set to `zigbee2mqtt`.
       You can change this if your Zigbee2MQTT setup uses a different base topic.

    3. **Actions**: For each button, configure the desired actions for single press,
       double press, and hold.

    **Notes:**

    - Ensure that your switch is correctly integrated with Zigbee2MQTT and Home
      Assistant.
    - The friendly name of the switch is used to dynamically construct the MQTT
      topic for handling actions.
    - This blueprint includes logging steps for debugging. Check the Home Assistant
      logs for information on received commands and matching conditions.
  domain: automation
  input:
    switch:
      name: TS004F Switch
      description: Tuya 4-Button Scene Switch to use
      selector:
        entity:
          domain: sensor
          integration: mqtt
          multiple: false
    button_one_short_press:
      name: Single Press - Button 1
      description: Action to run on button 1 (upper-left) single press
      default: []
      selector:
        action: {}
    button_one_hold:
      name: Hold - Button 1
      description: Action to run on button 1 (upper-left) hold
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Double Press - Button 1
      description: Action to run on button 1 (upper-left) double press
      default: []
      selector:
        action: {}
    button_two_hold:
      name: Hold - Button 2
      description: Action to run on button 2 (upper-right) hold
      default: []
      selector:
        action: {}
    button_two_double_press:
      name: Double Press - Button 2
      description: Action to run on button 2 (upper-right) double press
      default: []
      selector:
        action: {}
    button_two_short_press:
      name: Single Press - Button 2
      description: Action to run on button 2 (lower-right) single press
      default: []
      selector:
        action: {}
    button_three_short_press:
      name: Single Press - Button 3
      description: Action to run on button 3 (lower-left) single press
      default: []
      selector:
        action: {}
    button_three_hold:
      name: Hold - Button 3
      description: Action to run on button 3 (lower-left) hold
      default: []
      selector:
        action: {}
    button_three_double_press:
      name: Double Press - Button 3
      description: Action to run on button 3 (lower-left) double press
      default: []
      selector:
        action: {}
    button_four_short_press:
      name: Single Press - Button 4
      description: Action to run on button 4 (lower-right) single press
      default: []
      selector:
        action: {}
    button_four_hold:
      name: Hold - Button 4
      description: Action to run on button 4 (lower-right) hold
      default: []
      selector:
        action: {}
    button_four_double_press:
      name: Double Press - Button 4
      description: Action to run on button 4 (lower-right) double press
      default: []
      selector:
        action: {}
  source_url: https://raw.githubusercontent.com/lux4rd0/homeassistant/main/blueprints/zigbee2mqtt_tuya_4_button_scene_switch_ts004f.yaml
mode: single
max_exceeded: silent
variables:
  command: "{{ trigger.payload }}"
  topic: "{{ trigger.topic }}"
  switch_name: !input switch
  friendly_name: "{{ state_attr(switch_name, 'friendly_name') }}"
  friendly_name_processed: "{{ friendly_name | lower | replace(' ', '_') | replace('-', '_') | replace('_action', '') }}"
  topic_device_name: "{{ topic.split('/')[1] | lower | replace(' ', '_') | replace('-', '_') }}"
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/+/action
action:
  - service: system_log.write
    data:
      message: 'Received command {{ command }} from topic {{ topic }}'
      level: info
  - service: system_log.write
    data:
      message: 'Friendly name: {{ friendly_name }}, Processed: {{ friendly_name_processed }}'
      level: info
  - service: system_log.write
    data:
      message: 'Topic device name: {{ topic_device_name }}'
      level: info
  - service: system_log.write
    data:
      message: 'Match condition: {{ topic_device_name == friendly_name_processed }}'
      level: info
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ topic_device_name == friendly_name_processed }}"
        sequence:
          - service: system_log.write
            data:
              message: 'Matched device name: {{ friendly_name_processed }}'
              level: info
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ command == '1_single' }}"
                sequence: !input button_one_short_press
              - conditions:
                  - condition: template
                    value_template: "{{ command == '2_single' }}"
                sequence: !input button_two_short_press
              - conditions:
                  - condition: template
                    value_template: "{{ command == '3_single' }}"
                sequence: !input button_three_short_press
              - conditions:
                  - condition: template
                    value_template: "{{ command == '4_single' }}"
                sequence: !input button_four_short_press
              - conditions:
                  - condition: template
                    value_template: "{{ command == '1_double' }}"
                sequence: !input button_one_double_press
              - conditions:
                  - condition: template
                    value_template: "{{ command == '2_double' }}"
                sequence: !input button_two_double_press
              - conditions:
                  - condition: template
                    value_template: "{{ command == '3_double' }}"
                sequence: !input button_three_double_press
              - conditions:
                  - condition: template
                    value_template: "{{ command == '4_double' }}"
                sequence: !input button_four_double_press
              - conditions:
                  - condition: template
                    value_template: "{{ command == '1_hold' }}"
                sequence: !input button_one_hold
              - conditions:
                  - condition: template
                    value_template: "{{ command == '2_hold' }}"
                sequence: !input button_two_hold
              - conditions:
                  - condition: template
                    value_template: "{{ command == '3_hold' }}"
                sequence: !input button_three_hold
              - conditions:
                  - condition: template
                    value_template: "{{ command == '4_hold' }}"
                sequence: !input button_four_hold
